# Generated by Django 3.0.6 on 2020-07-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description lorem ipsum'),
            preserve_default=False,
        ),
    ]
